--require("alpha.lua")
require("plugin.colorscheme")
require("plugin.telescope")
require("plugin.treesitter")
-- require("plugin.neo-tree")
require("plugin.lualine")
require("plugin.lsp")
require("plugin.conform")
require("plugin.gitsigns")
require("plugin.trouble")
require("plugin.autoclose")
