# Kanagawa Wave Colors - https://github.com/rebelot/kanagawa.nvim/blob/master/extras/foot/kanagawa-wave.ini
[main]
include=~/.config/foot/themes/noctalia
initial-color-theme=dark
font=Cascadia Mono:size=14
shell=/usr/bin/zsh

